spring:
  application:
    name: eureka-consumer

server:
  port: 8904
eureka:
  instance:
    prefer-ip-address: true
    hostname: consumer
    appname: 消费者
  client:
    service-url:
      # 向server注册
      defaultZone: http://server2:8902/eureka/
