#server:
#  port: 8900
#eureka:
#  instance:
#    hostname: server
#    appname: 注册中心
#  client:
#    register-with-eureka: false # default true
#    fetch-registry: false # default true
#    service-url:
#      defaultZone: http://localhost:8900/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
#
#spring:
#  application:
#    name: eureka-server